# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays: 
1. A 1-D array called zeros having 10 elements and all the elements are set to zero. 
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’. 
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int. 
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13 
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [5]:
import numpy as np

# 1. A 1-D array called 'zeros' having 10 elements, all set to zero.
zeros = np.zeros(10)

# 2. A 1-D array called 'vowels' having the elements 'a', 'e', 'i', 'o', and 'u'.
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

# 3. A 2-D array called 'ones' having 2 rows and 5 columns, all set to 1, dtype as int.
ones = np.ones((2, 5), dtype=int)

# 4. A 2-D array called 'myarray1' using nested Python lists with specific data.
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])

# 5. A 2-D array called 'myarray2' using arange() with 3 rows and 5 columns, start value = 4, step size = 4, dtype as float.
myarray2 = np.arange(4, 4 * 5 * 3 + 1, 4, dtype=float).reshape(3, 5)

# Output the created arrays
print("zeros:\n", zeros)
print("vowels:\n", vowels)
print("ones:\n", ones)
print("myarray1:\n", myarray1)
print("myarray2:\n", myarray2)


zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
vowels:
 ['a' 'e' 'i' 'o' 'u']
ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]]
myarray1:
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
myarray2:
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following: 
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2. 
2. Reshape the array ones to have all the 10 elements in a single row. 
3. Display the 2nd and 3rd element of the array vowels. 
4. Display all elements in the 2nd and 3rd row of the array myarray1. 
5. Display the elements in the 1st and 2nd column of the array myarray1. 
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1. 
7. Reverse the array of vowels.

In [7]:
# 1. Find the dimensions, shape, size, data type, and itemsize of the arrays
arrays = [zeros, vowels, ones, myarray1, myarray2]
for array in arrays:
    print(f"Array: {array}")
    print(f"Dimensions: {array.ndim}")
    print(f"Shape: {array.shape}")
    print(f"Size: {array.size}")
    print(f"Data Type: {array.dtype}")
    print(f"Itemsize: {array.itemsize} bytes")
    print()

# 2. Reshape the array 'ones' to have all the 10 elements in a single row
ones_reshaped = ones.reshape(1, -1)
print("Reshaped 'ones':\n", ones_reshaped)

# 3. Display the 2nd and 3rd element of the array 'vowels'
print("2nd and 3rd elements of 'vowels':", vowels[1:3])

# 4. Display all elements in the 2nd and 3rd row of the array 'myarray1'
print("2nd and 3rd rows of 'myarray1':\n", myarray1[1:3])

# 5. Display the elements in the 1st and 2nd column of the array 'myarray1'
print("1st and 2nd columns of 'myarray1':\n", myarray1[:, 0:2])

# 6. Display the elements in the 1st column of the 2nd and 3rd row of the array 'myarray1'
print("1st column of the 2nd and 3rd rows of 'myarray1':", myarray1[1:3, 0])

# 7. Reverse the array of vowels
vowels_reversed = vowels[::-1]
print("Reversed 'vowels':", vowels_reversed)

Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimensions: 1
Shape: (10,)
Size: 10
Data Type: float64
Itemsize: 8 bytes

Array: ['a' 'e' 'i' 'o' 'u']
Dimensions: 1
Shape: (5,)
Size: 5
Data Type: <U1
Itemsize: 4 bytes

Array: [[1 1 1 1 1]
 [1 1 1 1 1]]
Dimensions: 2
Shape: (2, 5)
Size: 10
Data Type: int32
Itemsize: 4 bytes

Array: [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: float64
Itemsize: 8 bytes

Array: [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]
Dimensions: 2
Shape: (3, 5)
Size: 15
Data Type: float64
Itemsize: 8 bytes

Reshaped 'ones':
 [[1 1 1 1 1 1 1 1 1 1]]
2nd and 3rd elements of 'vowels': ['e' 'i']
2nd and 3rd rows of 'myarray1':
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
1st and 2nd columns of 'myarray1':
 [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]
1st column of the 2nd and 3rd rows of 'myarray1': [  3.4 -19. ]
Reversed 'vowels': ['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3. 
2. Add the arrays myarray1 and myarray2. 
3. Subtract myarray1 from myarray2 and store the result in a new array. 
4. Multiply myarray1 and myarray2 elementwise. 
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3. 
6. Divide myarray1 by myarray2. 
7. Find the cube of all elements of myarray1 and divide the resulting array by 2. 
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [9]:
import numpy as np

# Arrays created in the previous exercise
ones = np.ones((2, 5), dtype=int)
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 4 * 5 * 3 + 1, 4, dtype=float).reshape(3, 5)

# 1. Divide all elements of array 'ones' by 3
ones_divided = ones / 3
print("Array 'ones' divided by 3:\n", ones_divided)

# 2. Add the arrays 'myarray1' and 'myarray2'
# Note: They must have compatible shapes for addition.
myarray_sum = myarray1 + myarray2[:3, :3]  # Adjusting myarray2 for compatible shape
print("Sum of 'myarray1' and 'myarray2':\n", myarray_sum)

# 3. Subtract 'myarray1' from 'myarray2' and store the result in a new array
# Note: Adjusting myarray2 for compatible shape.
myarray_diff = myarray2[:3, :3] - myarray1
print("Difference of 'myarray2' and 'myarray1':\n", myarray_diff)

# 4. Multiply 'myarray1' and 'myarray2' elementwise
# Note: Adjusting myarray2 for compatible shape.
elementwise_product = myarray1 * myarray2[:3, :3]
print("Elementwise multiplication of 'myarray1' and 'myarray2':\n", elementwise_product)

# 5. Matrix multiplication of 'myarray1' and 'myarray2' and store in 'myarray3'
# Note: Adjusting shapes for matrix multiplication
myarray3 = np.dot(myarray1, myarray2[:3, :3].T)  # Transposing myarray2 to make it compatible
print("Matrix multiplication of 'myarray1' and 'myarray2' stored in 'myarray3':\n", myarray3)

# 6. Divide 'myarray1' by 'myarray2'
# Note: Adjusting myarray2 for compatible shape.
division_result = myarray1 / myarray2[:3, :3]
print("Division of 'myarray1' by 'myarray2':\n", division_result)

# 7. Find the cube of all elements of 'myarray1' and divide by 2
cubic_divided = (myarray1 ** 3) / 2
print("Cube of 'myarray1' divided by 2:\n", cubic_divided)

# 8. Find the square root of all elements of 'myarray2' and divide by 2
sqrt_divided = np.sqrt(myarray2) / 2
sqrt_divided_rounded = np.round(sqrt_divided, 2)
print("Square root of 'myarray2' divided by 2 (rounded to two decimal places):\n", sqrt_divided_rounded)


Array 'ones' divided by 3:
 [[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]
Sum of 'myarray1' and 'myarray2':
 [[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]
Difference of 'myarray2' and 'myarray1':
 [[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]
Elementwise multiplication of 'myarray1' and 'myarray2':
 [[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]
Matrix multiplication of 'myarray1' and 'myarray2' stored in 'myarray3':
 [[-1.3200e+01  8.0000e-01  1.4800e+01]
 [ 9.8400e+01  3.7840e+02  6.5840e+02]
 [ 8.7920e+02  2.7572e+03  4.6352e+03]]
Division of 'myarray1' by 'myarray2':
 [[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]
Cube of 'myarray1' divided by 2:
 [[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]


Using the arrays created above, write NumPy commands for the following: 
1. Find the transpose of ones and myarray2. 
2. Sort the array vowels in reverse. 
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [11]:
import numpy as np

# Arrays created in the previous exercise
ones = np.ones((2, 5), dtype=int)
vowels = np.array(['a', 'e', 'i', 'o', 'u'])
myarray1 = np.array([[2.7, 0, -2], [3.4, 10.6, 0], [-19, 99.9, 13]])
myarray2 = np.arange(4, 4 * 5 * 3 + 1, 4, dtype=float).reshape(3, 5)

# 1. Find the transpose of 'ones' and 'myarray2'
ones_transpose = ones.T
myarray2_transpose = myarray2.T

print("Transpose of 'ones':\n", ones_transpose)
print("Transpose of 'myarray2':\n", myarray2_transpose)

# 2. Sort the array 'vowels' in reverse order
vowels_sorted_reverse = np.sort(vowels)[::-1]
print("Vowels sorted in reverse order:\n", vowels_sorted_reverse)

# 3. Sort the array 'myarray1' such that it brings the lowest value of each column in the first row
# Using np.argsort to get indices that would sort the array, then indexing
sorted_indices = np.argsort(myarray1, axis=0)
sorted_myarray1 = myarray1[sorted_indices, np.arange(myarray1.shape[1])]

print("Sorted 'myarray1' by columns:\n", sorted_myarray1)


Transpose of 'ones':
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
Transpose of 'myarray2':
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]
Vowels sorted in reverse order:
 ['u' 'o' 'i' 'e' 'a']
Sorted 'myarray1' by columns:
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result. 

In [17]:
import numpy as np

# Create a 2-D array called 'myarray4' using arange() with 14 rows and 3 columns
myarray4 = np.arange(-1, -1 + 14 * 0.25, 0.25).reshape(14, 3)

# Split this array row-wise into 3 equal parts (4 rows each) and print the result
myarray4_split = np.split(myarray4, 3)
print("Split myarray4 into 3 equal parts:")
for part in myarray4_split:
    print(part, "\n")

ValueError: cannot reshape array of size 14 into shape (14,3)

Using the myarray4 created in the above questions, write commands for the following: 
1. Find the sum of all elements. 
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise. 
4. Find the max of all elements. 
5. Find the min of all elements in each row. 
6. Find the mean of all elements in each row. 
7. Find the standard deviation column wise.

#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.